function generate(){
  const nameStudent = document.getElementById('studentName').value;
  const description = document.getElementById('description').value;
  const date = document.getElementById('date').value;
  const time = document.getElementById('time').value;
  const caseId = document.getElementById('caseID').value;
  const generatorName = document.getElementById('generator').value;
  const nameFraud = document.getElementById('studentName2').value;
  const amount = document.getElementById('amount').value;
  const dueDate = document.getElementById('dueDate').value;
  caseText
  document.getElementById("caseId").innerHTML = "Case ID : # " + caseId;

  // case

  document.getElementById("caseText").innerHTML = `MR/MS ${nameFraud} you got a case based on your activity :  \n ${description} on ${date} ${time} , so you want to pay the fine as ${amount}₹ , Pay the amount before ${dueDate} | So dont make this mistake again , ok :) This case reported by ${nameStudent} . This case generated by ${generatorName}`;
  document.getElementById('r2').innerHTML = `cash for ${nameStudent} : ${amount * 30 / 100}₹ (30%)`;
  document.getElementById('r3').innerHTML = `cash for TEB INNOVATIONS : ${amount * 20 / 100}₹ (20%)`;
  document.getElementById('r4').innerHTML = `cash for ATL Lab : ${amount * 50 / 100}₹ (50%)`;
}

function printPage(){
  var body = document.getElementById("body").innerHTML;
  var data = document.getElementById("content").innerHTML;
  
  document.getElementById("body").innerHTML = data;
  window.print();
  document.getElementById("body").innerHTML = body;

}